import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ROOT_LAYOUT
 * layout.tsx
 * must include <html>, <body>
 * Next.js V12 - _app, _document
 */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body>
        <h1>layout</h1>
        {children}
      </body>
    </html>
  );
}
